openapi: 3.0.0
info:
  title: RevoU week 11 - Milestone 2
  version: 1.0.0
  description: Back-end API for Blog Posting
servers:
  - url: https://adriantori-w11-be.up.railway.app/api/v1
    description: 'Deployment Server'
tags:
  - name: Users
    description: Operations related to users
  - name: Posts
    description: Operations related to posts
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    registerNewUserRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 8
          pattern: "^[a-zA-Z0-9]+$"
paths:
  /register:
    post:
      summary: Register a user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerNewUserRequest'
      responses:
        '200':
          description: User registration successful
        '400':
          description: Input error
  /login:
    post:
      summary: Login a user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 1
                password:
                  type: string
                  minLength: 8
      responses:
        '200':
          description: User login successful
  /posts:
    post:
      summary: Create a new post
      tags:
        - Posts
      security:
        - bearerAuth: []
        - user: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postTitle:
                  type: string
                postBody:
                  type: string
      responses:
        '200':
          description: Post creation successful
    get:
      summary: Get all posts
      tags:
        - Posts
      security:
        - bearerAuth: []
        - user: []
        - admin: []
      responses:
        '200':
          description: List of posts
    patch:
      summary: Update a post
      tags:
        - Posts
      security:
        - bearerAuth: []
        - user: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postTitle:
                  type: string
                postBody:
                  type: string
                postId:
                  type: integer
      responses:
        '200':
          description: Post update successful
    delete:
      summary: Delete a post
      tags:
        - Posts
      security:
        - bearerAuth: []
        - admin: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: integer
      responses:
        '200':
          description: Post deletion successful

